services:
  postgres:
    image: postgres:16-alpine
    container_name: devsvault-postgres
    environment:
      POSTGRES_DB: devsvault
      POSTGRES_USER: devsvault
      POSTGRES_PASSWORD: devsvault_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devsvault -d devsvault"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: devsvault-api
    environment:
      DEVSVAULT_API_ADDR: ":8080"
      DEVSVAULT_MASTER_KEY_B64: "MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE="
      DEVSVAULT_AUTH_SIGNING_KEY: "MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE="
      DATABASE_URL: "postgres://devsvault:devsvault_dev_password@postgres:5432/devsvault?sslmode=disable"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/healthz >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: devsvault-web
    environment:
      NEXT_PUBLIC_API_URL: "http://api:8080"
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: devsvault-redis
    profiles: ["optional"]
    ports:
      - "6379:6379"

  cli:
    build:
      context: .
      dockerfile: apps/cli/Dockerfile
    profiles: ["tools"]
    environment:
      DEVSVAULT_API_URL: "http://api:8080"
    depends_on:
      api:
        condition: service_started

volumes:
  postgres-data: